# Generated by Django 4.1.6 on 2024-04-29 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=200)),
                ('reason_for_visit', models.TextField()),
                ('Employee_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.employee')),
            ],
        ),
    ]
